Sprint1
Iker-elorrieta/R1-2DM-1 pull request #1
Opened 2024-10-25 07:57 UTC by sergioortegaca

2024-10-25 07:58 UTC, gabrielLimari reviewed
Funciona

2024-10-25 09:12 UTC, Iker-elorrieta reviewed
Si podéis no subir la carpeta bin
Las imágenes no se ven en los cronómetros.
No esta hecho el histórico (se suponía que era para este sprint aunque habeis hecho otras partes)
No inicia el cronómetro de descanso.
Los cronómetros no hace falta que saquen los milisegundos
Intentar utilizar los mínimos mensajes de consola (trazas)
Muy bien implementado el MVC
Debemos de guardar en los backups cada uno de los elementos, no el arraylist entero.
Lo demás tiene muy buena forma.

2024-10-28 11:57 UTC, Iker-elorrieta requested changes
Siguen apareciendo trazas.
La forma de llamar a los backups no es la correcta.
Tarda mucho en cargar los workouts

2024-11-04 10:40 UTC, Iker-elorrieta requested changes
![image](https://github.com/user-attachments/assets/65b7354f-0c11-4683-858b-3f93268fb1dd)
No se puede ejecutar

2024-11-04 10:57 UTC, Iker-elorrieta requested changes
Hay warning. 
Hay textos que no se ven correctamente
![image](https://github.com/user-attachments/assets/06bdbd00-3800-437f-9cdf-006e8d5bb468)
![image](https://github.com/user-attachments/assets/a940506b-ee63-4746-8e4a-617b202690a2)
Hay warning. Hay textos que no se ven correctamente
La contraseña se ve, tiene que aparecer con puntos.

2024-11-06 07:13 UTC, Iker-elorrieta approved these changes
Sigue habiendo warnings

2024-11-06 07:13 UTC, merged